rapid7/insightappsec-azure-devops-extension

- tasks/InsightAppSec/task.json
Updated task version for consistency with project/package files.
> DF-2989 - Task version update

- tasks/InsightAppSec/task.json
- vss-extension.json
Author in `task.json` was previously that of the individual. Updated to `rapid7` to match the publisher. Also bumped versions.
> Author-Update - Update task.json author

- .github/workflows/ci.yml
- .github/workflows/publish.yml
Implement two Github Actions:
1. Building and CI of every commit
2. Creating tag/release and packaging/publishing to Visual Studio Marketplace on push to master
Avoid manually releasing new releases when approved and merged
> Implement Github Actions for CI on pushes and publish during release

- extension.spec.yaml
- help.md
Added spec and help files for hub prep.
> Hub Prep - Rapid7 InsightAppSec Azure DevOps Extension

- extension.spec.yaml
- Update to support products in spec
> Update products for hub spec

- extension.spec.yaml
- remove duplicate tag so it doesn't show for both use case and keyword
> Remove duplicate devops keyword

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- extension.spec.yaml
- help.md
- tasks/InsightAppSec/package.json
- tasks/InsightAppSec/task.json
- vss-extension.json
Updated task's package.json Node version to 12.14.1.
Build was previously failing due to Node errors.
Tested with a manual build + publish to private publisher.
> DF-3852A - Update to Node version

- README.md
- extension.spec.yaml
- help.md
- tasks/InsightAppSec/helpers/insightAppSecApi.ts
- tasks/InsightAppSec/task.json
- tasks/InsightAppSec/task.ts
- vss-extension.json
- Add content-type header and additional logging for application search lookup
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
> DF-4041: Add content-type header and additional logging for application search

- vss-extension.json
File missed in my previous checkin.
> Add file missed from my previous changelist.

- vss-extension.json
Added the new us2 and us3 regions to the dropdown list in "New Rapid7 InsightAppSec service connection
https://issues.corp.rapid7.com/browse/DF-4072
https://wiki.corp.rapid7.com/display/PC/2020+US+Regions+Launch++-+Project+Plan
Steps 13 and 14 here: https://wiki.corp.rapid7.com/display/EXT/ADO+v1.0.7+Test+Plan
- New feature (non-breaking change which adds functionality)
> Added us2 and us3 regions to service connection options

- README.md
- extension.spec.yaml
- help.md
- tasks/InsightAppSec/helpers/insightAppSecApi.ts
- tasks/InsightAppSec/task.json
- tasks/InsightAppSec/task.ts
- vss-extension.json
Added additional debug logging for improved request + response info
Customer is having an issue here https://issues.corp.rapid7.com/browse/LSI-1403 but we don't have sufficient logging to what where the issue with the request is
https://wiki.corp.rapid7.com/display/EXT/ADO+v1.0.8+test+plan
- New feature (non-breaking change which adds functionality)
> Release 1.0.8

- help.md
- manifest.json
- tasks/InsightAppSec/helpers/insightAppSecApi.ts
- tasks/InsightAppSec/task.json
- tasks/InsightAppSec/task.ts
- vss-extension.json
Removed duplicate file path name.
Removed duplicate line.
Solves issue with duplicate named file.
https://issues.corp.rapid7.com/browse/DF-4097
https://wiki.corp.rapid7.com/display/EXT/ADO+V1.1.1+TEST+PLAN
- Bug fix (non-breaking change which fixes an issue)
> DF-4097 Removing duplicate file path

- help.md
- manifest.json
- tasks/InsightAppSec/helpers/insightAppSecApi.ts
- tasks/InsightAppSec/task.json
- tasks/InsightAppSec/task.ts
- vss-extension.json
Amended the picklist for scan config to enable manual text entry, improved the logging in API class in case of incorrectly entered name
https://issues.corp.rapid7.com/browse/DF-4101
https://wiki.corp.rapid7.com/display/EXT/ADO+v1.1.2+test+plan
- Bug fix (non-breaking change which fixes an issue)
> DF-4101 - Release 1.1.2 - allowing manual entry of Scan Config Name

- vss-extension.json
Adjusting vss-extension page to allow for publication to Marketplace
> Changing vss-extension.json

- .github/CODEOWNERS
- Unimportant change to force publish of a new version of the app.
> Change to force new publish

- README.md
Minor update to match what's actually performed in the build
> Update readme build instructions

- help.md
- manifest.json
- tasks/InsightAppSec/helpers/insightAppSecApi.ts
- tasks/InsightAppSec/package-lock.json
- tasks/InsightAppSec/task.json
- vss-extension.json
Bumping ADO Dependencies, as identified by Dependabot.
follow-redirects: 1.14.5 -> 1.14.8
shelljs: 0.8.4 -> 0.8.5
Ran successfully with ADO
> DF-4194: Bumping ADO Dependencies

- manifest.json
- tasks/InsightAppSec/helpers/insightAppSecApi.ts
- tasks/InsightAppSec/package.json
- tasks/InsightAppSec/task.json
- vss-extension.json
Updating a number of dated dependencies to newer versions.
Snyk flagged some vulnerabilities in the previous versions of some dependencies.
Ran this locally and kicked off an IAS scan, both with and without gating with all reports enabled.
- Dependency updates (non-breaking change)
> IAS-11427: Updating dependencies and version

- manifest.json
- tasks/InsightAppSec/helpers/insightAppSecApi.ts
- tasks/InsightAppSec/package.json
- tasks/InsightAppSec/task.json
- vss-extension.json
Roll back breaking dependency changes
> IAS-11427: Roll back breaking changes

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- README.md
- manifest.json
- package.json
- tasks/InsightAppSec/helpers/insightAppSecApi.ts
- tasks/InsightAppSec/package-lock.json
- tasks/InsightAppSec/package.json
- tasks/InsightAppSec/task.json
- vss-extension.json
Updating node, typescript to allow for an updated axios version that snyk approves of.
Snyk flagged a number of issues with the axios version previously being used .
- Tested running the task locally
- Packaged and uploaded a test version of the extension to the market place under a private publisher, installed in a devops organization and ran pipelines using both self-hosted agents and azure hosted agents.
Versioning changes only.
Updated readme.
> IAS-11447: Updating node, typescript and axios versions
